package eu.pitlap.shared.core.data.resolver

import eu.pitlap.shared.core.data.models.ergast.MRData
import kotlinx.serialization.KSerializer
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.descriptors.element
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Yeah this was generated by AI. It doesn't look too good does it.
 */
object MRDataSerializer : KSerializer<MRData> {

    override val descriptor: SerialDescriptor =
        buildClassSerialDescriptor("MRData") {
            element<String>("xmlns")
            element<String>("series")
            element<String>("url")
            element<String>("limit")
            element<String>("offset")
            element<String>("total")
            element<JsonElement>("table")
        }

    override fun deserialize(decoder: Decoder): MRData {
        val input = decoder as? JsonDecoder
            ?: error("Only JSON supported")

        val obj = input.decodeJsonElement().jsonObject

        val tableEntry = obj.entries.firstOrNull {
            it.key.endsWith("Table")
        } ?: error("No table found in MRData")

        val table = input.json.decodeFromJsonElement(
            ErgastTableSerializer,
            tableEntry.value
        )

        return MRData(
            xmlns = obj["xmlns"]!!.jsonPrimitive.content,
            series = obj["series"]!!.jsonPrimitive.content,
            url = obj["url"]!!.jsonPrimitive.content,
            limit = obj["limit"]!!.jsonPrimitive.content,
            offset = obj["offset"]!!.jsonPrimitive.content,
            total = obj["total"]!!.jsonPrimitive.content,
            table = table
        )
    }

    override fun serialize(encoder: Encoder, value: MRData) {
        error("Serialization not supported")
    }
}
